# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](#30ff6e)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>]$time(bold green) """

[directory]
style = "#83e0fc"
truncation_length = 8
truncation_symbol = "…/"

[time]
disabled = false
format = '⌚[\[$time\]](#9eb299) '
time_format = "%T"
utc_time_offset = "local"

[python]
format = "via [🐍 $version](#43a1d8) "

[nodejs]
format = "via [🤖 $version](#43a1d8) "

[git_branch]
style = "#fcbe4b"
symbol = "🌱 "
truncation_length = 6
truncation_symbol = "~"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖"

[git_state]
cherry_pick = "[🍒PICKING](bold red)"
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "🏴"
deleted = "🚮"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "📝"
renamed = "👅"
staged = '[👀 \($count\)](#f7f0e3)'
stashed = "📦"
untracked = "🤷‍"
